


all: lib unit example

lib:
	cl.exe /Iinclude /c src/simdbitpacking.c src/simdintegratedbitpacking.c src/simdcomputil.c
	lib simdbitpacking.obj simdintegratedbitpacking.obj simdcomputil.obj /OUT:simdcomp.lib

unit: lib
	cl.exe /Iinclude src/unit.c /link simdcomp.lib

example: lib
	cl.exe /Iinclude example.c /link simdcomp.lib

clean:
	del *.obj
	del *.lib
	del *.exe

